# Scrapping

In [1]:
import selenium

In [13]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import time

 
options = Options()
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
options.add_argument("--window-size=1920,1080")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")


Positions = ["Data Engineer", "Data Science", "AI Developer", "Machine Learning Engineer"]
Jobs = []

driver = webdriver.Chrome(options=options)
driver.get("https://wuzzuf.net/")


for Position in Positions :    
    driver.find_element(By.NAME ,"q").clear()
    driver.find_element(By.NAME,'q').send_keys(Position)
    driver.find_element(By.XPATH,"//button[@type='submit']").click()
    time.sleep(2)
    driver.refresh()
    time.sleep(5)
    for Page in range (4):
        time.sleep(5)
        job_scraper = driver.find_elements(By.CSS_SELECTOR,".css-ghe2tq")
        time.sleep(5)
        for i in job_scraper :
            Job_Title = i.find_element(By.CLASS_NAME,'css-s5fwzh').text
            Company = i.find_element(By.CLASS_NAME,'css-ipsyv7').text
            Location = i.find_element(By.CLASS_NAME,'css-16x61xq').text
            try :
                Experience = i.find_element(By.XPATH, ".//span[contains(., 'Yrs of Exp')]").text.strip(" ·")
            except :
                Experience = 'No Experince Found'    
            Job_URL = i.find_element(By.CLASS_NAME,'css-o171kl').get_attribute('href')
            Jobs.append({
            "Job_Title" : Job_Title,
            "Company" : Company,
            "Location" : Location,
            "Experience" : Experience,
            "Job_URL" : Job_URL
            })
        try :
         driver.find_element(By.CSS_SELECTOR,"a[aria-label='Next page'] i[class='css-b80bsd efou2fk0'] svg").click()
        except :
         continue

# Small Transformation & File Save

In [14]:
import pandas as pd

Final = pd.DataFrame(Jobs)

In [15]:
Final

,Job_Title,Company,Location,Experience,Job_URL
0,Associate System Engineer “Associate Data Mana...,Target Integrated Systems -,"Cairo, Egypt",0 - 3 Yrs of Exp,https://wuzzuf.net/jobs/p/ubsrja3n94m1-associa...
1,Senior Data Engineer,Vertex Technologies -,"Cairo, Egypt",5+ Yrs of Exp,https://wuzzuf.net/jobs/p/3x6prdwpt2tz-senior-...
2,Data Center Facility Electrical/ Mechanical En...,GPX Egypt -,"New Cairo, Cairo, Egypt",3 - 5 Yrs of Exp,https://wuzzuf.net/jobs/p/39xm37penfcr-data-ce...
3,Data Engineer (Infrastructure & Operations),MEAHCO - Saudi German Health -,"Katameya, Cairo, Egypt",5 - 8 Yrs of Exp,https://wuzzuf.net/jobs/p/mhqqwhx31ryd-data-en...
4,Sr. Data Engineer - Spark,Techsa -,"Cairo, Egypt",7+ Yrs of Exp,https://wuzzuf.net/jobs/p/4w6f7tucldaf-sr-data...
...,...,...,...,...,...
207,Junior System Administrator,SHM Industries -,"Cairo, Egypt",1 - 2 Yrs of Exp,https://wuzzuf.net/jobs/p/esh3hhmwpxnt-junior-...
208,Junior GIS Technician,Citylogix ME -,"Katameya, Cairo, Egypt",0 - 3 Yrs of Exp,https://wuzzuf.net/jobs/p/9brwrgjkuyjv-junior-...
209,Maintenance & Technical Support Specialist,Infinity tecs -,"Cairo, Egypt",No Experince Found,https://wuzzuf.net/internship/okjfuagtatr5-mai...
210,Control Specialist & SCADA Operator,Alexandria Company for Vegetable Oils Extracti...,"Bourj Alarab, Alexandria, Egypt",0 - 2 Yrs of Exp,https://wuzzuf.net/jobs/p/lbhbijnit5gr-control...
211,Control Specialist & SCADA Operator,Alexandria Company for Vegetable Oils Extracti...,"Bourj Alarab, Alexandria, Egypt",0 - 2 Yrs of Exp,https://wuzzuf.net/jobs/p/lbhbijnit5gr-control...

In [18]:
Final = Final.drop_duplicates("Job_URL")

In [19]:
Final

,Job_Title,Company,Location,Experience,Job_URL
0,Associate System Engineer “Associate Data Mana...,Target Integrated Systems -,"Cairo, Egypt",0 - 3 Yrs of Exp,https://wuzzuf.net/jobs/p/ubsrja3n94m1-associa...
1,Senior Data Engineer,Vertex Technologies -,"Cairo, Egypt",5+ Yrs of Exp,https://wuzzuf.net/jobs/p/3x6prdwpt2tz-senior-...
2,Data Center Facility Electrical/ Mechanical En...,GPX Egypt -,"New Cairo, Cairo, Egypt",3 - 5 Yrs of Exp,https://wuzzuf.net/jobs/p/39xm37penfcr-data-ce...
3,Data Engineer (Infrastructure & Operations),MEAHCO - Saudi German Health -,"Katameya, Cairo, Egypt",5 - 8 Yrs of Exp,https://wuzzuf.net/jobs/p/mhqqwhx31ryd-data-en...
4,Sr. Data Engineer - Spark,Techsa -,"Cairo, Egypt",7+ Yrs of Exp,https://wuzzuf.net/jobs/p/4w6f7tucldaf-sr-data...
...,...,...,...,...,...
206,GIS Technician,Citylogix ME -,"Katameya, Cairo, Egypt",1 - 2 Yrs of Exp,https://wuzzuf.net/jobs/p/hlkkamp5vekw-gis-tec...
207,Junior System Administrator,SHM Industries -,"Cairo, Egypt",1 - 2 Yrs of Exp,https://wuzzuf.net/jobs/p/esh3hhmwpxnt-junior-...
208,Junior GIS Technician,Citylogix ME -,"Katameya, Cairo, Egypt",0 - 3 Yrs of Exp,https://wuzzuf.net/jobs/p/9brwrgjkuyjv-junior-...
209,Maintenance & Technical Support Specialist,Infinity tecs -,"Cairo, Egypt",No Experince Found,https://wuzzuf.net/internship/okjfuagtatr5-mai...
210,Control Specialist & SCADA Operator,Alexandria Company for Vegetable Oils Extracti...,"Bourj Alarab, Alexandria, Egypt",0 - 2 Yrs of Exp,https://wuzzuf.net/jobs/p/lbhbijnit5gr-control...

In [20]:
Final.to_csv("Final_Jobs.csv" , index=False)